name: Script check

on:
  push:
    branches: [ "sim", "wip" ]
  pull_request:
    branches: [ "sim", "wip" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Install shellcheck
      run: sudo apt-get update&&sudo apt-get install -y shellcheck

    - name: Run test script
      run: dash test.sh
